export const IconsNames = {
  Arrow: 'rill-icon-arrow',
  CheckboxChecked: 'rill-icon-checkbox-checked',
  CheckboxUnchecked: 'rill-icon-checkbox-unchecked',
  ZoomIn: 'rill-icon-zoom-in',
  ZoomOut: 'rill-icon-zoom-out',
  More: 'rill-icon-toggle-more',
  Save: 'rill-icon-save',
  Reset: 'rill-icon-reset',
  Clear: 'rill-icon-clear',
  Delete: 'rill-icon-delete',
  Cancel: 'rill-icon-cancel',
  Add: 'rill-icon-add',
  List: 'rill-icon-list',
  Lock: 'rill-icon-lock',
  Copy: 'rill-icon-copy',
  Paste: 'rill-icon-paste',
  Download: 'rill-icon-download',
  Upload: 'rill-icon-upload',
};
